### ISSUE TITLE
Does the function has_factory work correctly?

### ISSUE THREAD

**Issue by Jinhui-Wu** [noxrepo/nox#24]
In the head file openflow-inl-1.0.hh
// Factory
template<typename T>
struct has_factory
{
   // template <typename C> static char test(typeof(&C::factory));
    template <typename C> static char test(typeof(&C::factory()));  // something wrong?
    template <typename C> static long test(...);

public:
    enum { value = sizeof(test<T>(0)) == sizeof(char) };
};

All the openflow message class inherit from v1::ofp_msg which has a member function -- factory(), so has_factory will always return TRUE. Am I correct? 
I find this problem when I fail to send v1::ofp_port_stats_request.

**Comment by tootoonchian** [comment]
There I used a C++ template technique called SFINAE (http://en.wikipedia.org/wiki/Substitution_failure_is_not_an_error) to detect the types that have subclasses in order to construct and deserialize the correct openflow message subclass. (has_factory<T> will only be instantiated for such types and thus the correct construct_and_load struct will be selected.)
